Update android-ci.yml

diff --git a/.github/workflows/android-ci.yml b/.github/workflows/android-ci.yml
--- a/.github/workflows/android-ci.yml
+++ b/.github/workflows/android-ci.yml
@@ -25,8 +25,16 @@ jobs:
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
 
-    - name: Prepare configuration file
-      run: cp app/cassiaext.example.cfg app/cassiaext.cfg
+    -    - name: Prepare configuration file
+      run: |
+        if [ -f "app/cassiaext.example.cfg" ]; then
+          cp app/cassiaext.example.cfg app/cassiaext.cfg
+          echo "Configuration file copied successfully."
+        else
+          echo "Example config not found!"
+          exit 1
+        fi
+
 
     - name: Build Debug APK
       run: ./gradlew assembleDebug
